Algorithm implementation, partitioning, replication, database models and corrections
JuanM0412/Distributed_File_System pull request #10
Opened 2024-09-21 02:53 UTC by LuisaMG01

- Developed the GetDataNodesForUpload method to facilitate the selection of data nodes for file uploads.
- Implemented a weighted random selection strategy to distribute chunks among active data nodes, ensuring efficient utilization of storage.
- Created the MetaData model to encapsulate file metadata, including the file name, size, owner, and associated blocks.
- The GetDataNodesForUpload method saves metadata in the metaData collection after a successful data node selection.
- The UploadFile method manages the process of uploading a specified file in chunks to available data nodes. It handles the file's chunking, retrieves data nodes for storage, and sends each chunk to the designated nodes.
- The SendFile method is responsible for receiving a file chunk from the client and storing it on the data node. It manages the directory structure for user-specific file storage and updates the data node's available capacity.

2024-09-21 15:00 UTC, santiagoneusa commented on main_client.py
> +
why is this function commented?
if needed for later development, then delete the unnecessary blank spaces

2024-09-21 15:00 UTC, santiagoneusa commented on main_client.py
> +    #client.DownloadFile('test1.txt')
delete comment

2024-09-21 15:05 UTC, santiagoneusa commented on src/data_node/data_node.py
>          return data_node_pb2.Reply(length=file_size)
In other functions, the return statement has one space between itself and the line written before.

2024-09-21 15:08 UTC, santiagoneusa commented on src/models/namenode.py
> +class MetaData(BaseModel):
between the classes there has to be two spaces. run flak8 or black to format the code.

2024-09-21 15:09 UTC, santiagoneusa commented on src/name_node/name_node.py
>  from src.models.datanode import DataNode
dont put spaces between the imports.

2024-09-21 15:11 UTC, santiagoneusa approved these changes

2024-09-21 15:13 UTC, JuanM0412 commented on src/client/client.py
A lot of white spaces

2024-09-21 15:14 UTC, JuanM0412 commented on src/name_node/name_node.py
A lot of white spaces

2024-09-21 15:18 UTC, JuanM0412 approved these changes

2024-09-21 17:38 UTC, mahoyos commented on main_client.py
> +    #client.DownloadFile('test1.txt')
Borra ese registro quemado. Ya no debería ir ahí.

2024-09-21 17:40 UTC, mahoyos requested changes
Solo falta corregir las sugerencias pequeñas de formato en los comentarios y eliminar ese registro quemado. Hacer un commit con esas correcciones para proceder a aprobar

2024-09-22 16:11 UTC, srestrep74 approved these changes

2024-09-23 14:31 UTC, merged